[package]
name = "nessie"
version = "0.1.0"
authors = [ "joe.kaushal@gmail.com" ]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
deunicode = "1.3.0"
regex = "1.5.4"
bytesize = "1.0.1"

ahash = "0.7.4"
bumpalo = { version = "3.7.0", features = [ "allocator_api" ] }
hashbrown = { version = "0.11.2", features = [ "serde", "nightly", "bumpalo" ] }
smartstring = { version = "0.2.6", features = [ "serde" ] }

serde = { version = "1.0", features = [ "rc" ] }
serde-pickle = "0.6"
